name: AutoBackup (FTP)
on:
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch:
jobs:
  ProsesBackup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Menginstall Rclone
      run: curl https://rclone.org/install.sh | sudo bash
    - name: Memuat konfigurasi Rclone
      run: |
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${{ secrets.ftp }}
        EOF
    - name: Penyalinan
      run: |
        rclone copy tr: ts: --drive-server-side-across-configs --max-age 24h && rclone copy dr: ds: --drive-server-side-across-configs --max-age 24h && rclone copy da: db: --drive-server-side-across-configs --max-age 24h && rclone copy 1dr: 2dr: --drive-server-side-across-configs --max-age 24h && rclone copy 5dr: 6dr: --drive-server-side-across-configs --max-age 24h && rclone copy dr6666: 6dr: --drive-server-side-across-configs --max-age 24h && rclone copy "3dr:backup" "4dr:backup" --drive-server-side-across-configs --max-age 24h && rclone delete "kuy22:backup" --drive-use-trash=false && rclone copy kuy: kuy2: --drive-server-side-across-configs --max-age 24h
